---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: demo-password-1
spec:
  backendType: gcpSecretsManager
  data:
    - name: password
      key: demo-password-1
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: demo-password-2
spec:
  backendType: gcpSecretsManager
  data:
    - name: password
      key: demo-password-2
