---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: postgresql-secret
spec:
  backendType: gcpSecretsManager
  data:
    - name: demo-password-1
      key: demo-password-1
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: postgresql-secret
spec:
  backendType: gcpSecretsManager
  data:
    - name: demo-password-2
      key: demo-password-2
